language: c
sudo: required
env:
  global:
    # Travis limits maximum log size, we have to cut tests output 
    - CODECOV_TOKEN="987cf0f1-ae3b-477e-b645-954e682f99ec"
    - ZFS_TEST_TRAVIS_LOG_MAX_LENGTH=800
  matrix:
    # tags are mainly in ascending order
    - ZFS_BUILD_TAGS=0
    - ZFS_BUILD_TAGS=1
before_install:
   # - sudo apt-get -qq update
    - sudo apt-get install --yes -qq build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r) libaio-dev
    - sudo apt-get install --yes -qq zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev
    - sudo apt-get install lcov
    # packages for tests
    - sudo apt-get install --yes -qq parted lsscsi ksh attr acl nfs-kernel-server fio
    - sudo apt-get install --yes -qq libgtest-dev cmake
install:
    - pushd .
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - popd
    - cd ..
    - git clone https://github.com/zfsonlinux/spl
    - cd spl
    - git checkout spl-0.7.4
    - sh autogen.sh
    - ./configure
    - if [ $ZFS_BUILD_TAGS = 0 ]; then
        make;
      else
        make --no-print-directory -s pkg-utils pkg-kmod;
        sudo dpkg -i *.deb;
      fi
    - cd ../ZoL
    - sh autogen.sh
    - ./configure --enable-code-coverage=yes
    - make cstyle
    - if [ $ZFS_BUILD_TAGS = 0 ]; then
        ./configure --enable-code-coverage=yes --enable-debug --enable-uzfs=yes;
        make;
      else
        ./configure --enable-code-coverage=yes --enable-debug;
        make --no-print-directory -s pkg-utils pkg-kmod;
        sudo dpkg -i *.deb;
      fi
before_script:
    - make cstyle;
script:
    # run ztest and test supported zio backends
    - if [ $ZFS_BUILD_TAGS = 0 ]; then
        truncate -s 2G /tmp/ztest.1a;
        truncate -s 2G /tmp/ztest.2a;
        truncate -s 256M /tmp/ztest.log;
        travis_wait 60 ./tests/cbtest/gtest/test_uzfs && ./tests/cbtest/script/uzfs_cli.sh && ./cmd/uzfs_test/uzfs_test;
        travis_wait 10 ./cmd/ztest/ztest;
        truncate -s 100MB /tmp/disk;
        travis_wait 20 cmd/dmu_io_test/dmu_io_test tpool/vol /tmp/disk;
        sudo mknod /dev/fake-dev b 7 200;
        sudo chmod 666 /dev/fake-dev;
        sudo losetup /dev/fake-dev /tmp/disk;
        travis_wait 20 cmd/dmu_io_test/dmu_io_test tpool/vol /dev/fake-dev;
        sudo losetup -d /dev/fake-dev;
        sudo rm /dev/fake-dev;
        rm /tmp/disk;
      else
        if [ $TRAVIS_BRANCH = "zfs-0.7-release" ]; then
          travis_wait 100 /usr/share/zfs/zfs-tests.sh -r linux_cstor.run -v;
        else
          sudo /sbin/modprobe zfs;
          travis_wait 10 /sbin/ztest;
        fi
      fi
after_failure:
    - find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cut -c -$ZFS_TEST_TRAVIS_LOG_MAX_LENGTH {} \;
after_success:
    - find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cut -c -$ZFS_TEST_TRAVIS_LOG_MAX_LENGTH {} \;
    - bash <(curl -s https://codecov.io/bash)
